
@url="https://morning.jamsara.com"
@token= Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTAyZDlhMjVkNTQ0NTNiYzQyOWU1ZmEiLCJjaHVuayI6MSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjk4MzgzMjY3LCJleHAiOjIuMTc2NzgyMzM2MDAxNjk4NGUrMjF9.E5LDOQSPdIrbzcE3wXazYh6I8yS_YydVgH9T1MSyWLg


###############
POST https://morning.jamsara.com/api/dadmin/login HTTP/1.1
Content-type: application/json
# Authorization: {{token}}

{
   "username":"admin",
   "password":"123456" 
}
 

###  
POST https://morning.jamsara.com/api/dadmin/createImage HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
   "name": "Best Wishes",
   "image": "wishes.png"
}

###  
POST https://morning.jamsara.com/api/dadmin/getImageList HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTAyZDlhMjVkNTQ0NTNiYzQyOWU1ZmEiLCJjaHVuayI6MSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjk4MzgzMjY3LCJleHAiOjIuMTc2NzgyMzM2MDAxNjk4NGUrMjF9.E5LDOQSPdIrbzcE3wXazYh6I8yS_YydVgH9T1MSyWLg

{
    "keyWord": "Be",
    "pageNo": 1,
    "size": 10
}


    
###  
POST https://morning.jamsara.com/api/dadmin/getAllImage HTTP/1.1
Content-type: application/json
Authorization: {{token}}



###  
POST https://morning.jamsara.com/api/dadmin/updateImage HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "name": "User11",
    "image": "wishes.png"

}

### 
POST https://morning.jamsara.com/api/dadmin/deleteImage HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  "id": "653a2a2c24e1bcb575dc84d2"

}

###  
POST https://morning.jamsara.com/api/dadmin/updateImageStatus HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
   "id":  "653a2a2c24e1bcb575dc84d2"
}


###   
POST https://morning.jamsara.com/api/dadmin/createMessageSubCategory HTTP/1.1
Content-type: application/json
Authorization: {{token}}


{
   "name": "Best Wishes"
}

###  
POST https://morning.jamsara.com/api/dadmin/getMessageSubCategoryList HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{

   "keyWord": "",
    "pageNo": 1,
    "size": 10
}


###   
POST https://morning.jamsara.com/api/dadmin/getAllMessageSubCategory HTTP/1.1
Content-type: application/json
Authorization: {{token}}



###  
POST https://morning.jamsara.com/api/dadmin/updateMessageSubCategory HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "id": "653a2cc444ce87b75b286a30",
   "name": "update moment"
}


###  
POST https://morning.jamsara.com/api/dadmin/deleteMessageSubCategory HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{  

   "id": "653a2cc444ce87b75b286a30"
    
}

###  
POST https://morning.jamsara.com/api/dadmin/updateMessageSubCategoryStatus HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "id": "64c7848b0f36f0ae27ab9102"
}


###  
POST https://morning.jamsara.com/api/dadmin/createMessage HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  "messageSubCategoryId": "653a2cc444ce87b75b286a30",
  "message": "sdvgrfg"
}

###  
POST https://morning.jamsara.com/api/dadmin/updateMessage HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  "id": "653ba89d3dbfe0928a2fd502",
  "messageSubCategory": "653b5df12016de2c579ac789",
  "message": "Good wishes"


}


# ###  
# POST https://morning.jamsara.com/api/dadmin/getAllMessage HTTP/1.1
# Content-type: application/json
# Authorization: {{token}}


###   
POST https://morning.jamsara.com/api/dadmin/getMessageList HTTP/1.1
Content-type: application/json
Authorization: {{token}}


{
    "keyWord": "Go",
    "pageNo": 1,
    "size": 10
}


###  
POST https://morning.jamsara.com/api/dadmin/deleteMessgae HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  "id": "653a2f3f2d176fba88ed4b9d"
}


###  
POST https://morning.jamsara.com/api/dadmin/createQuotesSubCategory HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  "name": "Good Ouotes"
}

###  
POST https://morning.jamsara.com/api/dadmin/getQuotesSubCategoryList HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  
   "keyWord": "",
    "pageNo": 1,
    "size": 10
}

###  
POST https://morning.jamsara.com/api/dadmin/getAllQuotesSubCategory HTTP/1.1
Content-type: application/json
Authorization: {{token}}



###  
POST https://morning.jamsara.com/api/dadmin/updateQuotesSubCategory HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  "name": "653a399c5939c2c2ddbbea70"
}

###  
POST https://morning.jamsara.com/api/dadmin/deleteQuotesSubCategory HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  "id": "653a399c5939c2c2ddbbea70"
}

###  
POST https://morning.jamsara.com/api/dadmin/updateQuotesSubCategoryStatus HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  "id": "653a3b199fbf57c3f71dc7ac"
}




###  
POST https://morning.jamsara.com/api/dadmin/createQuotes HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "quotesSubCategoryId": "48617070792051756f746573",
    "quotes": "move"

}

# ###  
# POST https://morning.jamsara.com/api/dadmin/getAllQuotes HTTP/1.1
# Content-type: application/json
# Authorization: {{token}}


###  
POST https://morning.jamsara.com/api/dadmin/getQuotesList HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
   "keyWord": "",
    "pageNo": 1,
    "size": 10
}


###  
POST https://morning.jamsara.com/api/dadmin/updateQuotes HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{ 
    "id": "653b5f392016de2c579ac79d",
    "quotesSubCategoryId": "653b5cd92016de2c579ac781",
    "quotes": "Birthday Wishes"
}


###  
POST https://morning.jamsara.com/api/dadmin/deleteQuotes HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  "id": "653a3225035684bd127f8664"
}


###  
POST https://morning.jamsara.com/api/dadmin/updateQuotesStatus HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  "id": "653a373536efb4c064302a61"
}




###  
POST {{url}}/api/dadmin/createImageSubCategory HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  "name": "Ouotes test4"
}

###  
POST https://morning.jamsara.com/api/dadmin/getImageSubCategoryList HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  
   "keyWord": "",
    "pageNo": 1,
    "size": 10
}

###  
POST {{url}}/api/dadmin/getAllImageSubCategory HTTP/1.1
Content-type: application/json
Authorization: {{token}}



###  
POST {{url}}/api/dadmin/updateImageSubCategory HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  "id": "65448a03934f97b7919e1d17",
  "name": "Good Ouote2"
}

###  
POST {{url}}/api/dadmin/deleteImageSubCategory HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  "id": "65448a03934f97b7919e1d17"
}

###  
POST {{url}}/api/dadmin/updateImageSubCategoryStatus HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  "id": "653b60852016de2c579ac7a7"
}





